### ISSUE TITLE
Errore Appunti Fondamenti di Informatica

### ISSUE THREAD

**Issue by strzelca** [Matteo181202/Appunti-Informatica-UNIPI#2]
Ciao, ma a pagina 5 A intersezione B non dovrebbe essere x in A and x in B e non x in A or x in B (unione)?

**Comment by bigmat18** [comment]
Ciao, si guarda hai ragione, probabilmente è stato un errore effettuato con un copia ed incolla poi non corretto, grazie per avermelo fatto notare.
